name: CI/CD

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dist-path: ${{ steps.upload-artifact.outputs.artifact-path }}
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name : Show Dictionaries
        run: ls -la
      
      - name: Upload dist Folder as Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
      - name: Run test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures that this job runs after the 'build' job completes
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Deploy Application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          DEPLOY_HOST: ${{secrets.EC2_PUBLIC_IP}}
          DIST_DEPLOY_PATH: /home/ubuntu/deploy
        run: |
          set -e
          echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY"
          echo "DEPLOY_HOST: $DEPLOY_HOST"
          echo "DIST_DEPLOY_PATH: $DIST_DEPLOY_PATH"
          sudo apt-get update -y 
          sudo apt-get install -y openssh-client rsync   # Ensure SSH client is available
          eval $(ssh-agent -s)  # Start SSH agent
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key.pem  # Create key file
          chmod 400 private_key.pem  # Set the appropriate permissions for the key
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ls -la
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
          echo "Deploying to EC2 staging..."
          rsync -avz -e "ssh -i private_key.pem" ./dist/ ubuntu@$DEPLOY_HOST:$DIST_DEPLOY_PATH
          ssh -i "private_key.pem" ubuntu@$DEPLOY_HOST "
          echo 'Deployment complete!' && 
          ls -l $DIST_DEPLOY_PATH &&



